{
  "clean": true,
  "sdk": "macosx",
  "author": "Galen Rhodes",
  "author_url": "https://blog.projectgalen.com",
  "github_url": "https://github.com/GalenRhodes/Rubicon",
  "github_file_prefix": "https://github.com/GalenRhodes/Rubicon/blob/master",
  "theme": "fullwidth",
  "use_safe_filenames": true,
  "min_acl": "public",
  "undocumented_text": "",
  "title": "Rubicon©",
  "swift_build_tool": "xcodebuild",
  "build_tool_arguments": [ "-scheme", "Rubicon", "-destination", "platform=macOS,arch=x86_64", "-jobs", "12", ],
  "separate_global_declarations": true,
},
